# Generated by Django 2.2.17 on 2023-03-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_pl', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='course-organizer/')),
                ('image_pl', models.ImageField(null=True, upload_to='course-organizer/')),
                ('image_en', models.ImageField(null=True, upload_to='course-organizer/')),
            ],
        ),
    ]
