# Generated by Django 2.2.17 on 2023-03-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navoica_course', '0002_coursecategory_coursedifficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursedifficulty',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursedifficulty',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
