# Generated by Django 2.2.17 on 2023-03-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navoica_course', '0005_auto_20230328_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganizer',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
