# Generated by Django 2.2.17 on 2023-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navoica_course', '0006_courseorganizer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursedifficulty',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseorganizer',
            name='image_uk',
            field=models.ImageField(blank=True, null=True, upload_to='course-organizer/'),
        ),
        migrations.AddField(
            model_name='courseorganizer',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
