# Generated by Django 2.2.17 on 2021-10-11 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navoica_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRunOpinionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('grade', models.DecimalField(decimal_places=1, max_digits=2)),
                ('content', models.CharField(max_length=3000)),
                ('reviewed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='courserunopinionmodel',
            constraint=models.UniqueConstraint(fields=('course_id', 'user'), name='constraint'),
        ),
    ]
