# Generated by Django 2.2.17 on 2022-01-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navoica_api', '0002_auto_20211011_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserunopinionmodel',
            name='content',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
