# Generated by Django 2.2.17 on 2022-02-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navoica_api', '0003_auto_20220114_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('preface', models.CharField(max_length=1000)),
                ('employment_size', models.CharField(choices=[('FL', '1 etat'), ('DB', '2 etaty'), ('TR', '3 etaty'), ('HF', '1/2 etatu'), ('QR', '1/4 etatu')], default='FL', max_length=2)),
                ('localization', models.CharField(max_length=255)),
                ('offer', models.CharField(max_length=1000)),
                ('responsibilities', models.CharField(max_length=1000)),
                ('expectations', models.CharField(max_length=1000)),
                ('welcomed', models.CharField(max_length=1000)),
                ('attachment', models.CharField(max_length=3000)),
                ('link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
    ]
